## Session #1 Homework
#### ML Zoom Camp (Alexey Grigorev)
#### Richard Tran

---

### Set up the environment
You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can the instructions from [06-environment.md](06-environment.md).

In [1]:
# libraries
import numpy as np
import pandas as pd

### Question 1

What's the version of NumPy that you installed? 

You can get the version information using the `__version__` field:

```python
np.__version__
```

In [2]:
np.__version__

'1.20.1'

### Question 2

What's the version of Pandas? 

In [3]:
pd.__version__

'1.2.4'

### Getting the data 

For this homework, we'll use the same dataset as for the next session - the car price dataset.

Download it from [here](https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv).

You can do it with wget:

```bash
wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
```

Or just open it with your browser and click "Save as...".

Now read it with Pandas. 

In [4]:
# read in using pandas
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")

In [5]:
# peek at dataset
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

### Question 3

What's the average price of BMW cars in the dataset?


In [6]:
# apply filtering with summarizing operations
df[df["Make"] == "BMW"].MSRP.mean()

61546.76347305389

### Question 4

Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [7]:
# applying filtering with isnull() and & operator
# count how many values in subset
df[(df["Year"] >= 2015) & (df["Engine HP"].isnull())].Year.count()

51


### Question 5

* Calculate the average "Engine HP" in the dataset. 
* Use the `fillna` method and to fill the missing values in "Engine HP" with the mean value from the previous step. 
* Now, calcualte the average of "Engine HP" again.
* Has it changed? 

Round both means before answering this questions. You can use the `round` function for that:

```python
print(round(mean_hp_before))
print(round(mean_hp_after))
```

In [8]:
#calculate average engine hp (before)
round(df["Engine HP"].mean())

249

In [12]:
df["Engine HP"].isnull().sum()

69

In [13]:
#use fillna with mean value
df[["Engine HP"]] = df[["Engine HP"]].fillna(249)

In [14]:
df["Engine HP"].isnull().sum()

0

In [15]:
#calculate average engine hp (after)
round(df["Engine HP"].mean())

249

### Question 6

* Select all the "Rolls-Royce" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
* Now drop all duplicated rows using `drop_duplicates` method (you should get a dataframe with 7 rows).
* Get the underlying NumPy array. Let's call it `X`.
* Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
* Invert `XTX`.
* What's the sum of all the elements of the result?

Hint: if the result is negative, re-read the task one more time

In [18]:
# select rolls-royce cars
df2 = df[df["Make"] == "Rolls-Royce"]

In [19]:
df2

Make                   Model  Year             Engine Fuel Type  \
2921   Rolls-Royce                Corniche  2001  premium unleaded (required)   
3505   Rolls-Royce                    Dawn  2016  premium unleaded (required)   
5275   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5276   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5277   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5278   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5279   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5280   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5281   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5282   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5283   Rolls-Royce                   Ghost  2014  premium unleaded (required)   
5284   Rolls-Royce                   Ghost  2014  premium unleaded (required)   
7443   Rolls-Royce               Park Ward  2001  premium unleaded (required)   
7444   Rolls-Royce               Park Ward  2002  premium unleaded (required)   
7553   Rolls-Royce           Phantom Coupe  2014  premium unleaded (required)   
7554   Rolls-Royce           Phantom Coupe  2015  premium unleaded (required)   
7555   Rolls-Royce           Phantom Coupe  2016  premium unleaded (required)   
7556   Rolls-Royce  Phantom Drophead Coupe  2014  premium unleaded (required)   
7557   Rolls-Royce  Phantom Drophead Coupe  2015  premium unleaded (required)   
7558   Rolls-Royce  Phantom Drophead Coupe  2016  premium unleaded (required)   
7559   Rolls-Royce                 Phantom  2014  premium unleaded (required)   
7560   Rolls-Royce                 Phantom  2014  premium unleaded (required)   
7561   Rolls-Royce                 Phantom  2015  premium unleaded (required)   
7562   Rolls-Royce                 Phantom  2015  premium unleaded (required)   
7563   Rolls-Royce                 Phantom  2016  premium unleaded (required)   
7564   Rolls-Royce                 Phantom  2016  premium unleaded (required)   
9431   Rolls-Royce           Silver Seraph  2001  premium unleaded (required)   
9432   Rolls-Royce           Silver Seraph  2002  premium unleaded (required)   
11448  Rolls-Royce                  Wraith  2014  premium unleaded (required)   
11449  Rolls-Royce                  Wraith  2015  premium unleaded (required)   
11450  Rolls-Royce                  Wraith  2016  premium unleaded (required)   

       Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921       325.0               8.0         AUTOMATIC  rear wheel drive   
3505       563.0              12.0         AUTOMATIC  rear wheel drive   
5275       563.0              12.0         AUTOMATIC  rear wheel drive   
5276       563.0              12.0         AUTOMATIC  rear wheel drive   
5277       563.0              12.0         AUTOMATIC  rear wheel drive   
5278       563.0              12.0         AUTOMATIC  rear wheel drive   
5279       563.0              12.0         AUTOMATIC  rear wheel drive   
5280       563.0              12.0         AUTOMATIC  rear wheel drive   
5281       563.0              12.0         AUTOMATIC  rear wheel drive   
5282       563.0              12.0         AUTOMATIC  rear wheel drive   
5283       563.0              12.0         AUTOMATIC  rear wheel drive   
5284       563.0              12.0         AUTOMATIC  rear wheel drive   
7443       322.0              12.0         AUTOMATIC  rear wheel drive   
7444       322.0              12.0         AUTOMATIC  rear wheel drive   
7553       453.0              12.0         AUTOMATIC  rear wheel drive   
7554       453.0              12.0         AUTOMATIC  rear wheel drive   
7555       453.0              12.0         AUTOMATIC  rear wheel drive   
7556       453.0              12.0         AUTOMATIC  rear wheel drive   
7557       453.

In [20]:
# select only columns "Engine HP", "Engine Cylinders", "highway MPG"
df2[["Engine HP", "Engine Cylinders", "highway MPG"]]

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [24]:
# drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows)
df2 = df2[["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates()

In [25]:
df2

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [27]:
# get the underlying NumPy array. Let's call it X
X = df2.values

In [28]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [32]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
# transpose X
X.T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [34]:
#find XTX
XTX = (X.T).dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [35]:
# Invert XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [36]:
# What's the sum of all the elements of the result?
np.sum(XTX_inv)

0.032212320677486195


### Questions 7 

* Create an array `y` with values `[1000, 1100, 900, 1200, 1000, 850, 1300]`.
* Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
* What's the value of the first element of `w`?.

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

In [37]:
# create an array
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [38]:
# multiply inverse of XTX with transpose of X
w = (XTX_inv.dot(X.T)).dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])

In [39]:
# first element of w
w[0]

0.1998959818318624


## Submit the results

Submit your results here: https://forms.gle/aiunQqRtqcay8Wwo9.

If your answer doesn't match options exactly, select the closest one.

## Deadline

The deadline for submitting is 13 September 2021, 17:00 CET. After that, the form will be closed.

## Navigation

* [Machine Learning Zoomcamp course](../)
* [Lesson 1: Introduction to Machine Learning](./)
* Previous: [Summary](10-summary.md)